/**
 * Sift Solver — Double Latin Square with Hidden Locks
 *
 * 5x5 grid of tiles, each with a shape (0-4) and a color (0-4).
 * Goal: no repeated shape OR color in any row or column (double Latin square).
 * Some swap positions are secretly locked; failed swaps cost a move and reveal the lock.
 *
 * Key design: puzzles are generated by backward-scrambling from a solved state
 * through ONLY unlocked positions, but with cycle-based scrambles that create
 * entangled constraints requiring multi-step detours. Locks are then placed to
 * block direct resolution paths, forcing counterintuitive intermediary swaps.
 */

export const SIZE = 5;
export const NUM_SHAPES = 5;
export const NUM_COLORS = 5;

export type Tile = { shape: number; color: number };
export type SiftState = {
  grid: Tile[][];          // SIZE x SIZE grid
  locks: boolean[][];      // true = position is locked (hidden from player initially)
  knownLocks: boolean[][]; // locks discovered by player (revealed through failed swaps)
  moves: number;           // total moves taken (successful swaps + failed attempts)
  maxMoves: number;        // par / move limit
};

export type Move = {
  r1: number; c1: number;
  r2: number; c2: number;
};

export type Solution = {
  moves: Move[];
  steps: number;
  failedSwaps: number;
};

/* ─── RNG ─── */
function makeRng(seed: number) {
  let s = seed;
  return () => {
    s |= 0;
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* ─── Shuffle (Fisher-Yates) ─── */
function shuffle<T>(arr: T[], rng: () => number): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/* ─── Generate a valid Latin square ─── */
function generateLatinSquare(rng: () => number): number[][] {
  const base = [0, 1, 2, 3, 4];
  const firstRow = shuffle(base, rng);
  const rows: number[][] = [firstRow];
  const shifts = shuffle([1, 2, 3, 4], rng);
  for (const shift of shifts) {
    rows.push(firstRow.map((v) => (v + shift) % SIZE));
  }
  const colOrder = shuffle(base, rng);
  const rowOrder = shuffle([0, 1, 2, 3, 4], rng);
  return rowOrder.map((ri) => colOrder.map((ci) => rows[ri][ci]));
}

/* ─── Count violations ─── */
export function countViolations(grid: Tile[][]): number {
  let violations = 0;
  for (let r = 0; r < SIZE; r++) {
    const shapes = new Set<number>();
    const colors = new Set<number>();
    for (let c = 0; c < SIZE; c++) {
      shapes.add(grid[r][c].shape);
      colors.add(grid[r][c].color);
    }
    violations += (SIZE - shapes.size) + (SIZE - colors.size);
  }
  for (let c = 0; c < SIZE; c++) {
    const shapes = new Set<number>();
    const colors = new Set<number>();
    for (let r = 0; r < SIZE; r++) {
      shapes.add(grid[r][c].shape);
      colors.add(grid[r][c].color);
    }
    violations += (SIZE - shapes.size) + (SIZE - colors.size);
  }
  return violations;
}

/* ─── Heuristic: violations + penalty for tiles near locks ─── */
export function heuristic(state: SiftState): number {
  return countViolations(state.grid);
}

/* ─── Goal test ─── */
export function isGoal(state: SiftState): boolean {
  return countViolations(state.grid) === 0;
}

/* ─── Legal moves ─── */
export function legalMoves(state: SiftState): Move[] {
  const moves: Move[] = [];
  for (let r1 = 0; r1 < SIZE; r1++) {
    for (let c1 = 0; c1 < SIZE; c1++) {
      if (state.knownLocks[r1][c1]) continue;
      for (let r2 = r1; r2 < SIZE; r2++) {
        const c2Start = r2 === r1 ? c1 + 1 : 0;
        for (let c2 = c2Start; c2 < SIZE; c2++) {
          if (state.knownLocks[r2][c2]) continue;
          const t1 = state.grid[r1][c1];
          const t2 = state.grid[r2][c2];
          if (t1.shape === t2.shape && t1.color === t2.color) continue;
          moves.push({ r1, c1, r2, c2 });
        }
      }
    }
  }
  return moves;
}

/* ─── Apply move ─── */
export function applyMove(state: SiftState, move: Move): SiftState {
  const { r1, c1, r2, c2 } = move;
  const newGrid = state.grid.map((row) => row.map((t) => ({ ...t })));
  const newKnownLocks = state.knownLocks.map((row) => [...row]);

  if (state.locks[r1][c1] || state.locks[r2][c2]) {
    if (state.locks[r1][c1]) newKnownLocks[r1][c1] = true;
    if (state.locks[r2][c2]) newKnownLocks[r2][c2] = true;
    return {
      ...state,
      knownLocks: newKnownLocks,
      moves: state.moves + 1,
    };
  }

  const tmp = newGrid[r1][c1];
  newGrid[r1][c1] = newGrid[r2][c2];
  newGrid[r2][c2] = tmp;

  return {
    ...state,
    grid: newGrid,
    knownLocks: newKnownLocks,
    moves: state.moves + 1,
  };
}

/* ─── Generate puzzle ─── */
export function generatePuzzle(seed: number, difficulty: number): SiftState {
  const rng = makeRng(seed);

  // Generate the goal state: valid double Latin square
  const shapeSquare = generateLatinSquare(rng);
  const colorSquare = generateLatinSquare(rng);

  const goalGrid: Tile[][] = [];
  for (let r = 0; r < SIZE; r++) {
    goalGrid.push([]);
    for (let c = 0; c < SIZE; c++) {
      goalGrid[r].push({ shape: shapeSquare[r][c], color: colorSquare[r][c] });
    }
  }

  // Lock density: Mon ~12%, Fri ~28%
  const numLocks = 2 + difficulty; // diff 1->3, diff 5->7

  const locks: boolean[][] = Array.from({ length: SIZE }, () =>
    Array.from({ length: SIZE }, () => false)
  );

  // Place locks strategically: prefer central positions to block direct swaps
  const allPositions: [number, number][] = [];
  for (let r = 0; r < SIZE; r++) {
    for (let c = 0; c < SIZE; c++) {
      allPositions.push([r, c]);
    }
  }

  // Ensure at least 2 corners stay unlocked
  const corners = new Set(['0,0', '0,4', '4,0', '4,4']);
  let cornerLocks = 0;

  const shuffledPos = shuffle(allPositions, rng);
  let placed = 0;
  for (const [r, c] of shuffledPos) {
    if (placed >= numLocks) break;
    const isCorner = corners.has(`${r},${c}`);
    if (isCorner && cornerLocks >= 2) continue;
    locks[r][c] = true;
    if (isCorner) cornerLocks++;
    placed++;
  }

  // Get unlocked positions
  const unlocked: [number, number][] = [];
  for (let r = 0; r < SIZE; r++) {
    for (let c = 0; c < SIZE; c++) {
      if (!locks[r][c]) unlocked.push([r, c]);
    }
  }

  // Scramble using CYCLE permutations to create entangled constraints
  // A 3-cycle (A->B->C->A) requires 2 swaps to undo but creates coupled violations
  // that cannot be resolved by a single swap without temporarily worsening the state.
  const grid: Tile[][] = goalGrid.map((row) => row.map((t) => ({ ...t })));

  const numCycles = 1 + difficulty; // Mon: 2 cycles, Fri: 6 cycles
  const usedPositions = new Set<string>();

  for (let cycle = 0; cycle < numCycles; cycle++) {
    // Create 3-cycles among unlocked positions
    const available = unlocked.filter(([r, c]) => !usedPositions.has(`${r},${c}`));
    if (available.length < 3) break;

    const shuffled = shuffle(available, rng);
    const cyclePositions = shuffled.slice(0, 3);

    // Apply 3-cycle: A->B, B->C, C->A (rotate tiles)
    const [p0, p1, p2] = cyclePositions;
    const tmp = { ...grid[p0[0]][p0[1]] };
    grid[p0[0]][p0[1]] = { ...grid[p2[0]][p2[1]] };
    grid[p2[0]][p2[1]] = { ...grid[p1[0]][p1[1]] };
    grid[p1[0]][p1[1]] = tmp;

    for (const [r, c] of cyclePositions) {
      usedPositions.add(`${r},${c}`);
    }
  }

  // Additional random swaps for harder difficulties to further entangle
  const extraSwaps = Math.max(0, difficulty - 2);
  const remainingUnlocked = unlocked.filter(([r, c]) => !usedPositions.has(`${r},${c}`));
  for (let i = 0; i < extraSwaps && remainingUnlocked.length >= 2; i++) {
    const shuffled = shuffle(remainingUnlocked, rng);
    const [p1, p2] = shuffled;
    const tmp = grid[p1[0]][p1[1]];
    grid[p1[0]][p1[1]] = grid[p2[0]][p2[1]];
    grid[p2[0]][p2[1]] = tmp;
  }

  // Verify the puzzle isn't already solved
  if (countViolations(grid) === 0) {
    // Force disorder
    if (unlocked.length >= 2) {
      const [p1, p2] = shuffle(unlocked, rng);
      const tmp = grid[p1[0]][p1[1]];
      grid[p1[0]][p1[1]] = grid[p2[0]][p2[1]];
      grid[p2[0]][p2[1]] = tmp;
    }
  }

  const maxMoves = 10 + difficulty * 5;

  return {
    grid,
    locks,
    knownLocks: Array.from({ length: SIZE }, () =>
      Array.from({ length: SIZE }, () => false)
    ),
    moves: 0,
    maxMoves,
  };
}

/* ─── State key ─── */
function stateKey(state: SiftState): string {
  const gridKey = state.grid
    .map((row) => row.map((t) => `${t.shape}${t.color}`).join(''))
    .join('|');
  const lockKey = state.knownLocks
    .map((row) => row.map((v) => (v ? '1' : '0')).join(''))
    .join('');
  return `${gridKey}:${lockKey}`;
}

/* ─── Solver ─── */
export function solve(
  puzzle: SiftState,
  skillLevel: 1 | 2 | 3 | 4 | 5,
): Solution | null {
  switch (skillLevel) {
    case 1:
      return solveRandom(puzzle);
    case 2:
      return solveGreedy(puzzle);
    case 3:
      return solveGreedyLookahead(puzzle);
    case 4:
      return solveBeamSearch(puzzle, 100);
    case 5:
      return solveBeamSearch(puzzle, 1000);
  }
}

/* ─── Skill 1: Random valid moves ─── */
function solveRandom(puzzle: SiftState): Solution | null {
  let state = deepCopy(puzzle);
  const moveList: Move[] = [];
  let failedSwaps = 0;
  const maxSteps = 300;

  let rngSeed = 12345;
  function rng() {
    rngSeed |= 0;
    rngSeed = (rngSeed + 0x6d2b79f5) | 0;
    let t = Math.imul(rngSeed ^ (rngSeed >>> 15), 1 | rngSeed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  }

  for (let i = 0; i < maxSteps; i++) {
    if (isGoal(state)) return { moves: moveList, steps: moveList.length, failedSwaps };
    const moves = legalMoves(state);
    if (moves.length === 0) return null;
    const move = moves[Math.floor(rng() * moves.length)];
    const wasFailed = state.locks[move.r1][move.c1] || state.locks[move.r2][move.c2];
    state = applyMove(state, move);
    if (wasFailed) failedSwaps++;
    moveList.push(move);
  }
  return isGoal(state) ? { moves: moveList, steps: moveList.length, failedSwaps } : null;
}

/* ─── Skill 2: Greedy ─── */
function solveGreedy(puzzle: SiftState): Solution | null {
  let state = deepCopy(puzzle);
  const moveList: Move[] = [];
  let failedSwaps = 0;
  const maxSteps = 100;

  for (let i = 0; i < maxSteps; i++) {
    if (isGoal(state)) return { moves: moveList, steps: moveList.length, failedSwaps };
    const moves = legalMoves(state);
    if (moves.length === 0) return null;

    let bestMove = moves[0];
    let bestScore = Infinity;
    for (const m of moves) {
      const next = applyMove(state, m);
      const h = heuristic(next);
      if (h < bestScore) {
        bestScore = h;
        bestMove = m;
      }
    }

    const wasFailed = state.locks[bestMove.r1][bestMove.c1] || state.locks[bestMove.r2][bestMove.c2];
    state = applyMove(state, bestMove);
    if (wasFailed) failedSwaps++;
    moveList.push(bestMove);
  }
  return isGoal(state) ? { moves: moveList, steps: moveList.length, failedSwaps } : null;
}

/* ─── Skill 3: Greedy with 1-step lookahead ─── */
function solveGreedyLookahead(puzzle: SiftState): Solution | null {
  let state = deepCopy(puzzle);
  const moveList: Move[] = [];
  let failedSwaps = 0;
  const maxSteps = 80;

  for (let i = 0; i < maxSteps; i++) {
    if (isGoal(state)) return { moves: moveList, steps: moveList.length, failedSwaps };
    const moves = legalMoves(state);
    if (moves.length === 0) return null;

    let bestMove = moves[0];
    let bestScore = Infinity;

    for (const m of moves) {
      const next = applyMove(state, m);
      if (isGoal(next)) {
        moveList.push(m);
        return { moves: moveList, steps: moveList.length, failedSwaps };
      }
      const nextMoves = legalMoves(next);
      let bestNext = heuristic(next);
      for (const m2 of nextMoves.slice(0, 30)) {
        const next2 = applyMove(next, m2);
        bestNext = Math.min(bestNext, heuristic(next2));
      }
      if (bestNext < bestScore) {
        bestScore = bestNext;
        bestMove = m;
      }
    }

    const wasFailed = state.locks[bestMove.r1][bestMove.c1] || state.locks[bestMove.r2][bestMove.c2];
    state = applyMove(state, bestMove);
    if (wasFailed) failedSwaps++;
    moveList.push(bestMove);
  }
  return isGoal(state) ? { moves: moveList, steps: moveList.length, failedSwaps } : null;
}

/* ─── Skill 4-5: Beam search with A* flavor ─── */
function solveBeamSearch(puzzle: SiftState, beamWidth: number): Solution | null {
  type Beam = { state: SiftState; moves: Move[]; failedSwaps: number; cost: number };

  const init = deepCopy(puzzle);
  let beam: Beam[] = [{ state: init, moves: [], failedSwaps: 0, cost: 0 }];
  const maxDepth = 50;
  const visited = new Set<string>([stateKey(init)]);

  for (let depth = 0; depth < maxDepth; depth++) {
    const candidates: Beam[] = [];

    for (const entry of beam) {
      if (isGoal(entry.state)) return { moves: entry.moves, steps: entry.moves.length, failedSwaps: entry.failedSwaps };

      const legal = legalMoves(entry.state);
      const scored = legal.map((m) => {
        const next = applyMove(entry.state, m);
        const h = heuristic(next);
        const wasFailed = entry.state.locks[m.r1][m.c1] || entry.state.locks[m.r2][m.c2];
        return { m, next, h, wasFailed };
      });
      scored.sort((a, b) => a.h - b.h);

      const perEntry = Math.max(3, Math.ceil(beamWidth / Math.max(beam.length, 1)));
      for (const { m, next, wasFailed } of scored.slice(0, perEntry)) {
        const key = stateKey(next);
        if (visited.has(key)) continue;
        visited.add(key);

        candidates.push({
          state: next,
          moves: [...entry.moves, m],
          failedSwaps: entry.failedSwaps + (wasFailed ? 1 : 0),
          cost: entry.cost + 1,
        });
      }
    }

    if (candidates.length === 0) break;

    for (const c of candidates) {
      if (isGoal(c.state)) return { moves: c.moves, steps: c.moves.length, failedSwaps: c.failedSwaps };
    }

    // Score by f = cost + heuristic
    candidates.sort((a, b) => (a.cost + heuristic(a.state)) - (b.cost + heuristic(b.state)));
    beam = candidates.slice(0, beamWidth);
  }

  return null;
}

/* ─── Deep copy ─── */
function deepCopy(state: SiftState): SiftState {
  return {
    grid: state.grid.map((row) => row.map((t) => ({ ...t }))),
    locks: state.locks.map((row) => [...row]),
    knownLocks: state.knownLocks.map((row) => [...row]),
    moves: state.moves,
    maxMoves: state.maxMoves,
  };
}
